### ISSUE TITLE
Use imgui as an external dependency

### ISSUE THREAD

**Issue by SnarkBoojum** [anura-engine/anura#300] opened 2020-06-22 06:35 UTC
The current use of imgui through a git submodule (which needs to be fetched using 'git submodule update') isn't ideal :
1. After all, it's a dep like others, so why embed it?
2. It's a quite old version of imgui : upstream improved it since.

**Comment by DDR0** [comment] 2020-06-22 23:04
I agree, the submodule is not ideal.

However, for now, since upstream won't compile because things changed I
think that's a good reason not to use it. Regardless of any improvements.
The person who integrated imgui in the first place hasn't been active in a
while either, so I don't know why it was done like this in the first place
I'm afraid.

It's unlikely we'll upgrade imgui ourselves at this point, given most of
the use of it is in our dev tools. So we do recommend using the submodule
version for now.

**Comment by DDR0** [comment] 2020-06-23 09:32
Ah, this is a duplicate of issue #249.

**Closed as completed** 2020-06-23 09:32 UTC

**Comment by DDR0** [comment] 2020-06-23 09:34
Uh, anyway, if you'd like to talk to us in person, we're over on Discord at https://discord.gg/2MwMhdd. Might be more timely than the bugtracker here. :slightly_smiling_face:
